### PR TITLE
suggesting some "pt" translations for translation.json

### PR DESCRIPTION
**Pull request by civbruizer**

### CODE REVIEW

**Comment by henry232323** [comment]
Thanks for your help! I've gone ahead and added a few more phrases that need to be translated if you're still interested

**Comment by civbruizer** [comment]
Ok. will do it tomorrow. Thanks.

**Comment by civbruizer** [comment]
Hello, what should I do in this case?

"Type the number of the page you wish to jump to.\n1. Description\n2.
Picture\n3. Prefix"

Should i translate the "Description\n2" to "Descrição\n2" ??

the same thing in the \"no\" part, should I translate the no to \"não\"??

**Comment by henry232323** [comment]
Yes please translate all of those

**Comment by civbruizer** [comment]
I just read the translator's note for the yes/no, but the other question
still stands.

**Comment by henry232323** [comment]
> Should i translate the "Description\n2" to "Descrição\n2" ??
Yes

**Pull request merged**
